### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by likerino** [almajiro/larafilm#2]
Im trying for hours now to get this running on my local machine, cause i need some inspiration for my own project and learning. After first problems with CORS which i got fixed. It just shows cannot read property player of undefined and for images the same. I tried to fill the database but i don't really understand where the image/series/tv relation is. Cause there is none? or am i wrong. I can see the Episodes i created, Genres etc. in an array. please help me.

https://i.imgur.com/K5Dh3pO.png

**Comment by almajiro** [comment]
Thanks for open this issue.

This project does not work completely yet for a long time. because I am studying JavaScript and i want to understand what vue.js and video.js doing.

so i am finished to study javascript and started coding this project from 2 days ago.

this is a solution.

create the **kodi's tv show directory** and use `artisan import:tv` command to import library to laravel's database.
this command is automatically generates thumbnails, convert the video files to playable on browser and create relations.

for creating kodi's tv show, i recommend to use tinyMediaManager or MediaElch.

this is a directory structure

<img width="1337" alt="Screen Shot 2019-03-11 at 9 17 15 PM" src="https://user-images.githubusercontent.com/7089652/54123439-2245ad00-4443-11e9-8c8f-8fa151b7ba00.png">

but this command is required ffmpeg, so you need to install ffmpeg and setup correctly.

Sorry for my bad english.
Thank you.
